name: klustaviewa
dependencies:
- cython=0.23.4=py27_0
- dateutil=2.4.1=py27_0
- decorator=4.0.9=py27_0
- h5py=2.3.1=np18py27_0
- hdf5=1.8.15.1=vc9_4
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- jpeg=8d=vc9_0
- libpng=1.6.17=vc9_1
- libtiff=4.0.6=vc9_1
- matplotlib=1.3.1=np17py27_1
- msvc_runtime=1.0.1=vc9_0
- nose=1.3.7=py27_0
- numexpr=2.2.2=np17py27_2
- numpy=1.8.2=py27_0
- openssl=1.0.2g=vc9_0
- pandas=0.12.0=np17py27_1
- path.py=8.1.2=py27_1
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_0
- pyparsing=1.5.6=py27_0
- pyqt=4.10.4=py27_1
- pyreadline=2.1=py27_0
- pyside=1.2.1=py27_0
- pytables=3.0.0=np17py27_1
- python=2.7.11=2
- pytz=2016.2=py27_0
- qt=4.8.7=vc9_7
- scipy=0.13.2=np17py27_0
- setuptools=20.3=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_2
- pip:
  - galry
  - klusta
  - klustaviewa
  - klustakwik2
  - kwiklib
  - qtools

  - traitlets
  - joblib
  - vispy
  - phy
  - phycontrib

  - click==6.3
  - colorama==0.3.7
  - cookies==2.2.1
  - coverage==4.0.3
  - flake8==2.5.4
  - funcsigs==0.4
  - ipython-genutils==0.1.0
  - mccabe==0.4.0
  - mock==1.3.0
  - pbr==1.8.1
  - pep8==1.7.0
  - py==1.4.31
  - pyflakes==1.0.0
  - pyopengl==3.1.0
  - pytest==2.9.1
  - pytest-cov==2.2.1
  - python-dateutil==2.4.1
  - requests==2.9.1
  - responses==0.5.1
  - tables==3.0.0
  - tqdm==3.8.0
